name: common_utils_v2
description: a common utils for flutter project
version: 0.0.1
homepage: https://github.com/ilovesshan

environment:
  sdk: '>=3.0.0-0 <4.0.0'
  flutter: ">=3.13.9"

dependencies:
  flutter:
    sdk: flutter

  # 唤起三方应用
  url_launcher: ^6.2.1
  get: ^4.6.6
  # 网络请求
  dio: ^5.3.3
  # 屏幕适配插件
  flutter_screenutil: ^5.9.0
  # 上拉加载、下拉刷新插件
  flutter_easyrefresh: ^2.2.2
  # 图片预览插件
  photo_view: ^0.14.0
  # 图片选择器
  image_picker: ^1.0.3
  # 基于 微信 UI 的 Flutter 图片选择器
  wechat_assets_picker: ^8.7.1
  # 本地存储插件
  shared_preferences: ^2.2.2
  # 权限处理
  permission_handler: ^11.0.1
  # 图片下载
  image_gallery_saver: ^2.0.3
  # 图片缓存
  cached_network_image: ^3.3.0
  # 扫码插件
  barcode_scan2: ^4.2.4
  flutter_scankit: ^2.0.3
  # 网络检测插件
  connectivity: ^3.0.6
  # RSA加密插件
  encrypt: ^5.0.3
  # 表达式计算
  expressions: ^0.2.5+1
  # 卢轮播图插件
  flutter_swiper_plus: ^2.0.4
  # tabBar 小红点
  badges: ^3.1.2
  # UUID库
  uuid: ^4.1.0
  # 二维码生成插件
  qr_flutter: ^4.1.0
  # webview 插件
  webview_flutter: ^4.4.2
  flutter_webview_plugin: ^0.4.0
  # tabBar 插件
#  fancy_bottom_navigation: ^0.3.3
  curved_navigation_bar: ^1.0.3
  # 国际化
  # flutter_cupertino_localizations: ^1.0.1
  flutter_localized_locales: ^2.0.5
  # flutter应用一键更新
  flutter_xupdate: ^3.0.0
  # app版本信息
  package_info_plus: ^4.2.0
  # 录音插件
  flutter_sound_lite: ^8.5.0
  # 文件路径
  path_provider: ^2.1.0
  # 气泡提示
  just_the_tooltip: ^0.0.12
  # socket api
  web_socket_channel: ^2.4.0
  # toast 轻提示
  fluttertoast: ^8.2.2
  bot_toast: ^4.1.1
  flutter_easyloading: ^3.0.5
  # 简单自动完成(模糊搜索)`
  flutter_typeahead: ^4.8.0
  # 监听键盘弹出/关闭
  flutter_keyboard_visibility: ^5.4.1
  # flutter闪屏页
  flutter_native_splash: ^2.3.5
  # 日志工具
  logger: ^2.0.2+1
  # 设备信息
  device_info_plus: ^9.1.0
  # Flutter的SQLite插件
  sqflite: ^2.3.0
  # 图片压缩
  flutter_image_compress: ^2.1.0
  # 更新应用程序徽章
  flutter_app_badger: ^1.5.0
  # 应用程序(快捷启动菜单)
  quick_actions: ^1.0.6
  # 处理英语单词
  english_words: ^4.0.0
  # 显示和推送Flutter本地通知
  flutter_local_notifications: ^16.1.0
  # 文本复制到剪贴板并从剪贴板粘贴
  clipboard: ^0.1.3
  # 获取地理位置信息
  geolocator: ^10.1.0
  # 视频播放
  chewie: ^1.7.1
  video_player: ^2.8.1
  # 随机中英文名
  username: ^0.2.3
  # 汉字转拼音
  lpinyin: ^2.0.3
  # 时间库
  intl: ^0.18.1
  # Dart后台任务调度
  workmanager: ^0.5.1
  # HTML解析
  flutter_widget_from_html_core: ^0.14.6
  # 加载lottie动画
  lottie: ^2.7.0
  # 验证码组件
  pinput: ^3.0.1
  # 访问日历
  device_calendar: ^4.3.1
  timezone: ^0.9.2
  # 百分比 进度条指示器
  percent_indicator: ^4.2.3
  # 读取SVG资源文件
  flutter_svg: ^2.0.9
  # 资源分享
  share_plus: ^7.2.1
  # 时间日期选择器
  flutter_datetime_picker_plus: ^2.1.0

# 依赖版本覆盖
dependency_overrides:
  # flutter_xupdate 依赖所引用版本
  package_info_plus: ^3.0.3
  # flutter_sound_lite 依赖所引用版本
  logger: ^1.1.0
  uuid: ^3.0.1
  http: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

  # 生成文件的通用命令
  build_runner: '2.1.2'

flutter: