name: common_utils_v2
description: A Common Utils For Flutter project.
version: 0.0.1
homepage: https://github.com/ilovesshan

environment:
  # dart sdk 2.12.0 开始支持空安全
  sdk: ">=2.12.0 <3.0.0"
  # flutter 2.12.0 开始支持空安全
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

  # 唤起三方应用
  url_launcher: ^6.0.10
  get: ^4.6.0
  # 网络请求
  dio: ^4.0.6
  # 全局toast插件
  flutter_easyloading: ^3.0.5
  # 屏幕适配插件
  flutter_screenutil: ^5.5.3+2
  # 上拉加载、下拉刷新插件
  flutter_easyrefresh: ^2.2.1
  # 图片预览插件
  photo_view: ^0.14.0
  # 图片选择器
  image_picker: ^0.8.4+1
  # 本地存储插件
  shared_preferences: ^2.0.7
  # 权限处理
  permission_handler: ^8.1.6
  # 图片下载
  image_gallery_saver: ^1.7.1
  # 图片缓存
  cached_network_image: ^3.2.0
  # 扫码插件
  barcode_scan2: '4.2.1'
  flutter_scankit: ^1.2.4
  # 网络检测插件
  connectivity: ^3.0.6
  # RSA加密插件
  encrypt: ^5.0.0
  # 表达式计算
  expressions: '0.2.3'
  # 卢轮播图插件
  flutter_swiper_plus: ^2.0.4
  # tabBar 小红点
  badges: ^2.0.3
  # UUID库
  uuid: ^3.0.6
  flutter_typeahead: ^3.1.0
  # 二维码生成插件
  qr_flutter: ^4.0.0
  # webview 插件
  webview_flutter: '2.0.13'
  flutter_webview_plugin: '0.4.0'
  # tabBar 插件
  fancy_bottom_navigation: ^0.3.3
  curved_navigation_bar: ^1.0.3
  # 国际化
  flutter_cupertino_localizations: ^1.0.1
  # flutter应用一键更新
  flutter_xupdate: ^2.0.3
  # app版本信息
  package_info_plus: ^1.3.0
  fluttertoast: ^8.2.1
  # 录音插件
  flutter_sound_lite: ^8.5.0
  # 文件路径
  path_provider: ^2.0.4
  # 气泡提示
  just_the_tooltip: ^0.0.11+2
  # socket api
  web_socket_channel: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:

  assets:
    - assets/common/